import { type NextPage } from 'next';
import Head from 'next/head';
import GameCanvas from '@components/GameCanvas';

const Home: NextPage = () => {
  function renderGameCanvas() {
    if (typeof window === 'undefined') {
      return null;
    }

    return <GameCanvas />;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-center bg-black" style={{ height: '100svh', width: '100svw' }}>
        {renderGameCanvas()}
      </main>
    </>
  );
};

export default Home;
